name: build
on: [push]
jobs:
  job1:
   name: Build
   runs-on: ubuntu-latest
   steps:
     - name: Check Repository
       uses: actions/checkout@v4
     - name: Upload File
       uses: actions/setup-node@v4
       with:
         node-version: '14'
